### ISSUE TITLE
4☆ RNG

### ISSUE THREAD

**Issue by kfnguyen** [AguzzTN54/Genshin-Impact-Wish-Simulator#10]
The game's rules state that if the first 4☆ that you pull isn't a featured 4☆, then the next 4☆ is guaranteed to be a featured 4☆. But this sim frequently pulls two 4☆ in a row that aren't featured 4☆. It's not a big deal, but would be good to address for accuracy.

![Screenshot 2022-04-07 135221](https://user-images.githubusercontent.com/19743798/162300649-8b34135d-1392-4a67-8dd4-5831aa86d47c.png)

**Comment by AguzzTN54** [comment]
Really ? Uh, I didn't notice that.
I'll renew the algorithm in the next deployment .

**Comment by AguzzTN54** [comment]
The problem was fixed in 05a6e7b830c7db829e459b8b40adc2f6ab7c3f61.
Thanks for your attention .
