### ISSUE TITLE
Primordial Jade Winged-Spear must be in standart and weapon banner

### ISSUE THREAD

**Issue by vellasha** [AguzzTN54/Genshin-Impact-Wish-Simulator#13]
I think you forgot about that spear lol.

**Comment by AguzzTN54** [comment]
nice 😅 thanks for your attention, I forgot to add slingshot to the Standard list too.
So, both weapons have added in this commit ba8a37ea208de0f15e6db879c2306243b93bb803 . I wish it works right now
![WishSimulator App - 4_21_2022, 11_47_39 PM](https://user-images.githubusercontent.com/13815468/164517547-5d4e6662-2957-4235-848b-ad4eef472486.png)
