### ISSUE TITLE
Limited Browser supports 

### ISSUE THREAD

**Issue by AguzzTN54** [AguzzTN54/Genshin-Impact-Wish-Simulator#14]
I found some feedback saying that the display looks messed up in the Safari browser both on iPhone and Mac .
For now I can't solve this problem cuz I don't have an iOS environment to test and improve the styles.
I hope there are kind people can help until I find the way how to solve it

**Comment by AguzzTN54** [comment]
Not only in Safari, the web app looks messed up when opened in other browsers such as baidu dan UC browser

Since I can't fix it soon, so I highly recommend to using Firefox or a browser with Chromium technology, like Google Chrome, Ms.Edge, Brave, Kiwi, Duckduckgo, Tor, and others

**Comment by AguzzTN54** [comment]
work done so far is using postcss and autoprefixer ( 0d6730c ) to automatically generate CSS code that supported in various browser, but I don't really know is't useful to fix this issue, I still can't test it because of device limitations

**Comment by dionysuses** [comment]
You could try
https://stackoverflow.com/questions/1825599/testing-web-application-on-mac-safari-when-i-dont-own-a-mac

**Comment by AguzzTN54** [comment]
Thanks, So far I'm using [playwright ](https://playwright.dev/) for end-to-end testing on webkit browsers like safari, this is very helpful, everything is working fine, but I'm not too sure as long as I don't test directly on the iOS ecosystem 😄
