### ISSUE TITLE
Wish simulator issue

### ISSUE THREAD

**Issue by Ad3ptusXi4o** [AguzzTN54/Genshin-Impact-Wish-Simulator#17]
Hello there!
My wish simulator has an issue, idk if it's just mine or not but the last version is 2.6 but we are already in 2.7 and I rly want to pull for yelan in the simulator so yeah would be really cool if you could fix that

**Comment by AguzzTN54** [comment]
Hiii .. you can go to [https://wishsimulator.app](https://wishsimulator.app) to pull on the latest banner.
You should find Yelan banner there, I always update on time.

If you still don't see Yelan banner, please try to clear site data by pressing **CTRL + Shift + i** then go to **Application** -> **Storage** then press **clear site data**
![Screenshot 2022-06-16 134732](https://user-images.githubusercontent.com/13815468/174009316-c875e2a5-4f82-42b3-a15b-63b0cf64fb0c.png)
If you use mobile phone, press three dot on the top right of the browser -> settings -> Site Settings -> All SItes -> Select https/wishsimulator.app -> press **Clear and Reset**


For Your Information. I will not update the other domain anymore, different domains aren't synchronized, sometimes it will make user confused, so I will focus to [WishSimulator.App](https://wishsimulator.app) only
