### ISSUE TITLE
[Question] Complete Data for 2.7 Patch

### ISSUE THREAD

**Issue by ookamiiixd** [AguzzTN54/Genshin-Impact-Wish-Simulator#20]
Seems like the 2.7 patch data in this repo isn't complete. While seems like it's available on the production site, i can't find data such as 2.7 Itto banner and Shinobu data in this repo.

Just to clarify, i also make a Genshin Impact wish simulator app which is inspired from this app, but as a discord bot. The bot is dependent on this repo for its data. I hope you keep updating this repo.

Also, i've contacted you on Twitter asking for permissions, but seems like you're really active there. I hope you're okay with this.

Thank you.

**Comment by AguzzTN54** [comment]
I'm glad this project inspiring you.
I already push the the latest changes to this repository, you can use everything you want to support your project. I hope your work is going well
