### ISSUE TITLE
online hosting?

### ISSUE THREAD

**Issue by salsawij** [AguzzTN54/Genshin-Impact-Wish-Simulator#27]
nvermind.

**Comment by salsawij** [comment]
if you don't mind, how do I host this online excluding vercel? the ads are super annoying

**Comment by AguzzTN54** [comment]
1. Do you have problem with ads from this App ?
    You can go to [/src/lib/components/utility/Iklan.svelte](https://github.com/AguzzTN54/Genshin-Impact-Wish-Simulator/blob/master/src/lib/components/utility/Iklan.svelte#L1) to remove it.
2. For deployment, there are many adapters that you can use, see the list here 👉[Svelte-Kit Community-Provided Adapter](https://sveltesociety.dev/components/#Sveltekit%20Adapters).
  If you're not familiar with all of that things, you don't need to change anything, then after running build command, just grab the static files from `.vercel_build_output/static`, you can deploy it to [Github Pages](https://pages.github.com/), [Firebase](https://console.firebase.google.com/), [Render](https://render.com/), [Fly](https://fly.io/), [Glitch](https://glitch.com/), [Netlify](https://www.netlify.com/), [Surge](https://surge.sh), [Cloudflare](https://pages.cloudflare.com/) Cpanel Hosting, or whatever you can

**Comment by salsawij** [comment]
alright, thanks so much!

**Comment by salsawij** [comment]
so, i'm hosting a website here, right. But I'm still new with this, do you have any idea how to put the html file code and run the app?

**Comment by AguzzTN54** [comment]
I see.. It seems that the `_app` folder is not processed during the build process. I'll try to reproduce this issue, for now you can find other service to deploy the app since I just realize there's a problem with github pages

**Comment by AguzzTN54** [comment]
So, fyi Github pages is built with Jekyll and during the build process, all files and folder with underscore (_) prefix will be ignored, to bypass it just create a new file with name `.nojekyll` in the root of repository.

**Comment by salsawij** [comment]
> So, fyi Github pages is built with Jekyll and during the build process, all files and folder with underscore (_) prefix will be ignored, to bypass it just create a new file with name `.nojekyll` in the root of repository.

works great! thank you!!

**Comment by salsawij** [comment]
by the way, I have another problem here. I want to add the app as a part of my website, how do I add it? I don't quite get how to use the cname recordd and apex domain, (my website is hosted using ip address)

**Comment by AguzzTN54** [comment]
You can't use an ip address, you need to have a domain or subdomain first . An Apex domain means the domain that you have full control of it. Maybe [this post](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site) can help you

**Comment by salsawij** [comment]
> You can't use an ip address, you need to have a domain or subdomain first . An Apex domain means the domain that you have full control of it. Maybe [this post](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site) can help you

alright, thank you!

**Comment by salsawij** [comment]
hello, is it possible to customize this? 
![image](https://user-images.githubusercontent.com/106524854/187155051-11b06dcf-733f-488c-ae14-25260347f3d3.png)
I want add symbol and other name for the screenshot share

**Comment by AguzzTN54** [comment]
Yeah,  it's possible, but please don't forget to give a credit to creator

**Comment by salsawij** [comment]
> Yeah, it's possible, but please don't forget to give a credit to creator

how do I do it? I left the repository available as credit

**Comment by AguzzTN54** [comment]
You can edit WishResult.svelte

**Comment by salsawij** [comment]
> You can edit WishResult.svelte

thanks!!
