### ISSUE TITLE
Display after press button 'Skip'

### ISSUE THREAD

**Issue by QuyetAQ** [AguzzTN54/Genshin-Impact-Wish-Simulator#3]
After press 10 roll, the wish screen is displayed. I press 'Skip' button but the list of 10 items is not displayed, instead it is displayed one by one.
I think you should fix it to give the most game-like experience.
Thanks.

**Comment by AguzzTN54** [comment]
Uh, I almost forgot about that, thanks for remind me.
I had pushed some adjustment to implement the function that you mean today c528b8ebb795ee7a2b6b8ab5a056deaddc59f39d. I hope it working correctly right now

**Comment by QuyetAQ** [comment]
It's fine, thank you.
