### ISSUE TITLE
50/50s

### ISSUE THREAD

**Issue by yeahimkitten** [AguzzTN54/Genshin-Impact-Wish-Simulator#31]
ive learnt that the 50/50 system is actually not 50/50, its not randomized whatsoever, you lose 1 then win 1 and it goes on like that, i think it would create a more realistic experience with an actual 50/50 ^_^

**Comment by AguzzTN54** [comment]
Can you tell me which banner that has the problem?

As you know, I created an algorithm based on in-game details
- For example: in the Event Banner, the first 5* item is 50/50, no guarantee to lose or win.
- If you win, your next 5* is 50/50 again, there is no guarantee you will lose.
- If you lose, your next 5* is guaranteed to get the promoted item.
- Once you get the promoted item, your next 5* is 50/50 again, no guarantee to lose or win.

I've tested Character Event Banner about 1300 pulls, I won 7x and lost 7x , it is 50% win and 50% lose. So I still don't notice anything wrong.
However after receiving your feedback I would consider to add a win/lose/guarantee indicator to the wish history and analytics on it.

**Comment by yeahimkitten** [comment]
i think ive mostly pulled on the new yoimiya banner, but its been
consistently one win and one lose one after the other, i know that you can
win two 50/50s in a row in genshin and that never happened to me on the
website

**Comment by AguzzTN54** [comment]
Okay.. after trying to test it again, I still didn't find the problem as you described before. As you can see bellow, I won  3x in a row on the website 
![image](https://user-images.githubusercontent.com/13815468/184085137-25fe6abe-a860-436a-b0a4-9b2e42373dab.png)

At the end, the result depends on the player's luck. Just like me, I've never won 50/50 in a row more than 1x. So maybe you are unlucky in this simulator.
