### ISSUE TITLE
Banner and Primo Issue

### ISSUE THREAD

**Issue by Awdasdwafxdfasfasdasdvbfxc** [AguzzTN54/Genshin-Impact-Wish-Simulator#38]
My banner is still in 2.7 and I can't open the gift and recommened part of shop

**Comment by AguzzTN54** [comment]
Hello. This app is officially deployed to [https://wishsimulator.app/](https://wishsimulator.app/).
I only own this domain and always update the banner on time. If you're from another site, maybe they haven't updated their site with latest code from this repository.
