### ISSUE TITLE
links to malicious websites.  

### ISSUE THREAD

**Issue by ColoredHearts** [AguzzTN54/Genshin-Impact-Wish-Simulator#39]
Whenever I click a new tab opens up obviously to a website that wants to harm my pc. Please fix. Your are the only up to date wishing simulator and I would hate not being able to wish on it anymore.

**Comment by AguzzTN54** [comment]
I'll reduce the number of ads soon..
If you can't wait for now, I recommend you to use [Wrap](https://1.1.1.1/)  or [Adguard](https://adguard.com/) to prevent ads and any malicious links.
This is very useful not only in this simulator, but every single site you're open will be filtered. It's free, I'm not going to give you a referral links.
