### ISSUE TITLE
Lisa impossible to get?

### ISSUE THREAD

**Issue by Danielpicasso314** [AguzzTN54/Genshin-Impact-Wish-Simulator#41]
I've gotten every single character on the standard banner, even c6 amber and c6 kaeya, but not a single Lisa. Am I just really unlucky or is there something else going on?

Here is a screenshot of my inventory:
![Screenshot 2022-10-07 164323](https://user-images.githubusercontent.com/115320512/194649670-140a479d-de36-44b9-a430-7c4937ed4874.jpg)

**Comment by AguzzTN54** [comment]
it's possible to get Lisa, just like any other character.
As you know, new characters will be released after a certain time, many characters make the chance to get certain characters reduced, I suggest you to switch banners to version 1.0, you will not get the newest characters in there, so you have more chances to get Lisa

![image](https://user-images.githubusercontent.com/13815468/194708676-bbda2961-876c-456d-abb3-e8041db7bab1.png)

![image](https://user-images.githubusercontent.com/13815468/194708267-384c6f93-a1cf-4990-b56b-d23b0175217d.png)
