### ISSUE TITLE
The Weapon banner rates might be wrong

### ISSUE THREAD

**Issue by ScarletSeal** [AguzzTN54/Genshin-Impact-Wish-Simulator#46]
Normally you have a 75% chance to get one of the two featured weapons (with 37.5% each) and 25% to get a weapon from the standard banner. Since after a standard banner weapon you're always guaranteed to get one of the two featured weapons, you'd expect a 80-20 split between featured-standard. 

Today I was running a few simulations when I noticed I was getting too many standard weapons, so I booted up my pc and ran a macro until I got 100 5 star weapons. Instead of getting an 80-20 distribution, I got 66 featured weapons, and 34 from the standard banner, indicative of a 50/50 split when you don't have a guaranteed.

![Immagine](https://user-images.githubusercontent.com/118117643/201529556-12de26a3-e288-4c40-af3c-966f3823bf85.png)

**Comment by ScarletSeal** [comment]
![Immagine2](https://user-images.githubusercontent.com/118117643/201530586-4b557b3c-0d0c-4248-93f7-174209a53e10.png)

164 weapons: 57 (34.75%) are from the standard banner, 107 (65.24%) are featured

**Comment by AguzzTN54** [comment]
Oh wow, you are very thorough about it.
I just realized that I set the rate for the weapon banner incorrectly. Besides, the rate-up weapon should have a 75% chance as well.

So, I'll fix it later and refactor the code that's still messy.  Thanks.
