### ISSUE TITLE
Kokomi's name is spelt wrong

### ISSUE THREAD

**Issue by barbatosboon** [AguzzTN54/Genshin-Impact-Wish-Simulator#49]
In the simulator, Kokomi's name was spelt "Sagonomiya Kokomi", not "Sangonomiya Kokomi."
![Screenshot 2022-12-01 8 16 52 AM](https://user-images.githubusercontent.com/119605790/205075725-9ba6861e-7bd0-45f4-a1ac-53f03329bcb5.png)

**Comment by AguzzTN54** [comment]
I see.. I will fix it on the next update along with 3.3 release.
Thanks for your attention!
