### ISSUE TITLE
Sangonomiya Kokomi bug again

### ISSUE THREAD

**Issue by enjiloved** [AguzzTN54/Genshin-Impact-Wish-Simulator#50]
When I came back, Sangonomiya Kokomi wasn't in my inventory (When I enabled "Show ALL Charatcers")
The next thing I saw was when I disabled the "Show All Characters" I saw there was a bug with Kokomi that says "Sangonomiya-Kokomi.Name" when you click on her.
When the option "Show All Characters" is disabled, there are two different kokomis.
<img width="961" alt="image" src="https://user-images.githubusercontent.com/120356640/206965153-d39e7d05-08bd-4213-9212-58a62c269dcc.png">
<img width="961" alt="image" src="https://user-images.githubusercontent.com/120356640/206965421-3bb16a43-1306-470b-beb4-a66ed6afaaa8.png">

**Comment by AguzzTN54** [comment]
Ah, I see, it happens because the app still read the browser caches.
Actually, clearing the data from menu will fix this issue, but You will lose your whole history. I will take a look soon and add some function to combine the old caches with the new data.

**Comment by AguzzTN54** [comment]
I've made some changes to update kokomi's name on User's Storage. Can you check it? I hope this will fix the issue.

**Comment by AguzzTN54** [comment]
I'm so sorry, it seems you will not be able to verify this issue because I have changed the domain, and all data from the old domain will no longer be used.
