### ISSUE TITLE
It says that I can do a ten pull even though I can't

### ISSUE THREAD

**Issue by barbatosboon** [AguzzTN54/Genshin-Impact-Wish-Simulator#51]
![Screenshot 2022-12-16 10 29 41 PM](https://user-images.githubusercontent.com/119605790/208443595-86391e41-902f-449a-acf0-8286a84f5ea0.png)

**Comment by AguzzTN54** [comment]
![OnPaste 20221220-162956](https://user-images.githubusercontent.com/13815468/208632674-75138608-b00a-4ef6-8679-7032e0b788d6.jpg)
Do you mean the button ?
I have fix it, it should work properly now .
