### ISSUE TITLE
The details for Standard Banner is supposed to say "4 star" instead of "5 star" in the bottom part.

### ISSUE THREAD

**Issue by barbatosboon** [AguzzTN54/Genshin-Impact-Wish-Simulator#52]
![Screenshot 2022-12-19 8 25 38 AM](https://user-images.githubusercontent.com/119605790/208447887-e1ec912a-6e78-47f4-88b2-34d9d1873767.png)

**Comment by AguzzTN54** [comment]
Thanks for the attention, some translations still don't include the variable to change the rarity automatically, so I've fixed it, I hope it shows up as expected by now.
