### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by Sunny-JP** [AguzzTN54/Genshin-Impact-Wish-Simulator#54]
Hi.
I am Japanese. I saw this simulator does not support Japanese , so I tried to make a file. However, I have no skills like programming. I do not know if the file I created is what you want, but if it is appropriate, I would be happy if you add it to the simulator!
(I have also created translated files for characters and weapons)
[ja-JP.zip](https://github.com/AguzzTN54/Genshin-Impact-Wish-Simulator/files/10368460/ja-JP.zip)

**Comment by AguzzTN54** [comment]
Great, let me check first.
You have worked very well, thank you for your dedication to making this translation, I really appreciate it.

**Comment by AguzzTN54** [comment]
I have added them to the Simulator, maybe you can review it again, if there is any text out of place, please let me know!
You really helped me a lot :)

**Comment by Sunny-JP** [comment]
I am glad I could help you too. Please check that there were just a few translation errors (due to my mistakes).
(If you are aiming for a perfect work) Japanese "kanji" and Chinese "kanji" differ in some parts. I recommend using Japanese fonts when you switch to Japanese. I have attached a comparison chart.
![00000151](https://user-images.githubusercontent.com/122193933/211228773-5f560d6b-b783-401b-948c-b65ead1b1b95.png)

**Comment by AguzzTN54** [comment]
I see. I'll looking for the Japanese font and add it to the site.
Genshin Impact's font file size is too big, so I need to do some optimization first, I hope it won't take too much time

**Comment by Sunny-JP** [comment]
Yes, it is. Unfortunately, the file size is large due to the large number of kanji...
Since there are more Chinese characters than Japanese ones, there are many cases where Japanese is displayed in Chinese fonts. I have made a suggestion, but it may be better to leave it as it is now.
Keeping the website smooth should be a priority over detailed design.

**Comment by AguzzTN54** [comment]
I've added some fonts for this case, they should look different now.
I've also subset the fonts, so site performance won't be affected as much

**Comment by Sunny-JP** [comment]
Very well done! Thank you for all the great work you do.
