### ISSUE TITLE
Resetting Data

### ISSUE THREAD

**Issue by Thatsverysuggestivethanks** [AguzzTN54/Genshin-Impact-Wish-Simulator#63]
I needed my pity counter reset every 70-90 pulls, to do that I had to reset the entire page data (not cache)
It would be very helpful if we had options to reset without resetting the page settings i.e. the unlimited fates option, skip animation, banner stages, etc. And more importantly, thank you for making this.

**Comment by AguzzTN54** [comment]
Actually, I have added a button to clear gacha history for each banner. The Site settings will not be affected if you delete the data from History Page.

![OnPaste 20230208-080241](https://user-images.githubusercontent.com/13815468/217402118-55680e5c-3bda-4dcd-8636-3408bdd2f9aa.jpg)
