### ISSUE TITLE
This app contains extremely annoying ads or pop-up ads that make it unusable.

### ISSUE THREAD

**Issue by HidemaruOwO** [AguzzTN54/Genshin-Impact-Wish-Simulator#66]
![image](https://user-images.githubusercontent.com/82384920/219431037-db5fefbe-16da-403f-8029-342d106a8715.png)
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/82384920/219431845-12b1eb65-7b19-49c6-a046-bf1df54fb7de.png">

The 'Wish Simulator' is a great product compared to others, but it becomes difficult to use due to full-screen ads and malicious fake alert ads that appear.

If this is not intended by the developers, I would like to submit a pull request for a version of the app with the ads removed.

**Comment by AguzzTN54** [comment]
Thank you for your feedback, actually the site has an option to remove ads. If you feel uncomfortable with it, I recommend to turn on adblocker or build the project on your machine/site .

**Comment by HidemaruOwO** [comment]
わかりました。そのようにさせていただきます。
