### ISSUE TITLE
Yanfei on 1.3 weapon banner?

### ISSUE THREAD

**Issue by kgoggg** [AguzzTN54/Genshin-Impact-Wish-Simulator#76]
Hi there, I pulled Yanfei along with Staff of Homa during its original banner. Yanfei was not released at that point.
![image](https://user-images.githubusercontent.com/129635903/229326436-e04fd068-c789-42e9-bd1b-2047df44026a.png)

**Comment by AguzzTN54** [comment]
![image](https://user-images.githubusercontent.com/13815468/229333969-8233ee99-ad39-4bbd-81c5-f81e5d016123.png)
Thanks for your report, You mean this banner ?
I've removed Yanfei from that banner, and I've fixed the same issue for Xinyan and Diona.
