### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by popopop830214** [AguzzTN54/Genshin-Impact-Wish-Simulator#84]
Here are some spelling mistakes in Genshin Impact Wish Simulator:

- Standard Banner says "Standard whises have no time limit.", it should be "Standard wishes have no time limit."

- Wish History:
1) "Total Spend" should be "Total Spent".
2) "Primogem" should be "Primogems". 
3) "Total Pull" should be "Total Pulls".

- Paimon's Bargains: "Exchange with Primogem" should be "Exchange with Primogems"

- When you get a character constellation: Right now it says "Convertion", it should be just "Convert"

That's all the mistakes I've caught so far.

**Comment by AguzzTN54** [comment]
I see, thank you for your corrections.
I think there are still a lot of mistakes, because I'm not a native speaker.

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by AguzzTN54** [comment]
For now, you can go to `locales` folder to review the translation files [https://github.com/AguzzTN54/Genshin-Impact-Wish-Simulator/tree/master/src/locales](https://github.com/AguzzTN54/Genshin-Impact-Wish-Simulator/tree/master/src/localesl)

I'll looking for an easier way to collaborate with Translations.
