### ISSUE TITLE
Traditional Chinese translation and hope add NTD

### ISSUE THREAD

**Issue by wibe01204** [AguzzTN54/Genshin-Impact-Wish-Simulator#94]
here is Traditional Chinese !
[zh-TW.zip](https://github.com/AguzzTN54/Genshin-Impact-Wish-Simulator/files/13299749/zh-TW.zip)

**Comment by wibe01204** [comment]
By the way, I hope the currency can be added to the New Taiwan Dollar (NTD)

**Comment by wibe01204** [comment]
> Oh, thank you! I'll check as soon as possible. Could you please provide information on the price list in NTD or where I can find it?

Here
https://guidetotaiwan.com/en/article/currency-new-taiwan-dollar-twd

**Comment by AguzzTN54** [comment]
Well, I've added this localization. I hope I've included the correct price list as well.
I really appreciate your contribution.
